# Generated by Django 4.2.16 on 2025-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_webhooks', '0008_alter_webhook_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('STUDENT_REGISTRATION_COMPLETED', 'Student registration completed'), ('SESSION_LOGIN_COMPLETED', 'Session login completed'), ('COURSE_ENROLLMENT_CREATED', 'Course enrollment created'), ('COURSE_ENROLLMENT_CHANGED', 'Course enrollment changed'), ('COURSE_UNENROLLMENT_COMPLETED', 'Course unenrollment completed'), ('CERTIFICATE_CREATED', 'Certificate created'), ('CERTIFICATE_CHANGED', 'Certificate changed'), ('CERTIFICATE_REVOKED', 'Certificate revoked'), ('COHORT_MEMBERSHIP_CHANGED', 'Cohort membership changed'), ('COURSE_DISCUSSIONS_CHANGED', 'Course discussions changed'), ('COURSE_CREATED', 'Course created'), ('COURSE_PUBLISHED', 'Course published')], default='', help_text='Event type', max_length=50),
        ),
    ]
